# Generated by Django 2.2 on 2019-04-29 21:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20190430_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edNo', models.IntegerField()),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('fromDate', models.DateField(default=datetime.date.today)),
                ('toDate', models.DateField(default=datetime.date.today)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'edNo')},
            },
        ),
    ]
