# Generated by Django 2.2 on 2019-04-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='isConnected',
            field=models.IntegerField(default=0),
        ),
    ]
