# Generated by Django 2.2 on 2019-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobLocation',
            field=models.CharField(max_length=150),
        ),
    ]
