# Generated by Django 2.2.1 on 2019-05-05 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
